### PR TITLE
fix apparmor profile for Arch Linux

### PR DESCRIPTION
**Pull request by glitsj16**
This fixes https://github.com/netblue30/fdns/issues/44.

### CODE REVIEW

**Comment by glitsj16** [comment]
I think we need to backport this to 0.9.62.10 or cut a new release containing the patch...

**Comment by rusty-snake** [comment]
If the AA profile fails with nscd, does it fail with sssd too?

**Comment by glitsj16** [comment]
> If the AA profile fails with nscd, does it fail with sssd too?

@rusty-snake Good question. I have zero experience with sssd but I see there is a community package in Arch repo's and some wiki info. I'll try to test things in that context. Thanks for pointing it out.

**Comment by netblue30** [comment]
> I think we need to backport this to 0.9.62.10 or cut a new release containing the patch...

New release in a few days, it is much easier. @sblighting @startx2017 ?

**Comment by sblighting** [comment]
I'll check in some fixes today.

**Comment by sblighting** [comment]
all in

**Pull request merged**
