### PR TITLE
typo

### PR DESCRIPTION
**Pull request by Fred-Barclay**
Hey @netblue30 ... just a typo fix (I believe).

I was thinking of writing a systemd service file for this so it could be automatically started at boot w/o messing with /etc/rc.local... would that be useful? I've got a draft one written already but still need to test it out.

### CODE REVIEW

**Comment by netblue30** [comment]
Sure, go for it. Also, if you are still on Arch, what source code packages did you have to install to get it compiled? I did develop this thing on Arch, but I don't remember what I had to install.

**Comment by Fred-Barclay** [comment]
Still on Arch. :smile: I didn't have to install anything extra, but I have so much dev stuff already on this system... I'll set up a fresh VM and see what we need.

**Comment by Fred-Barclay** [comment]
@netblue30 turns out the openssl library and libseccomp are included by default (with the 'base' package). Do you want to list build dependencies too? If so `gcc` and `make` are the only things needed on Arch (they're installed by default also if the `base-devel` group is installed during initial setup, but this isn't always the case).

**Comment by netblue30** [comment]
Not gcc, just compile dependencies on openssl if any, so I can add it here on README (.md)

>    Debian/Ubuntu: sudo apt-get install libseccomp-dev libssl-dev
>    Fedora/CentOS: sudo yum install libseccomp-devel openssl-devel

**Comment by Fred-Barclay** [comment]
@netblue30 no you're good then, openssl is pulled in by `iputils` which is part of the `base` group.

**Comment by netblue30** [comment]
cool, thanks!

**Pull request merged**
